name: Django CI

on:
  push:
    branches: [ "main","dev" ] # dev추가
  pull_request:
    branches: [ "main","dev" ] # dev추가

jobs:
  build:

    runs-on: ubuntu-latest
    services:  # ✅ 여기 추가됨
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3] # 자신의 버전과 맞추기 python --version

    env:  # ✅ 환경 변수도 설정
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # 신버전으로 올리기
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
